[package]
name = "chip8-rust"
version = "0.1.0"
authors = ["Francois Brodeur <francois.brodeur@adgear.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"
rand = "0.7.2"

